version: '4.8'

services:
  openssl:
    image: alpine/openssl
    volumes:
      - ./certs:/etc/ssl/certs
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "if [ ! -f /etc/ssl/certs/ca-key.pem ]; then 
        mkdir -p /etc/ssl/certs && 
        openssl genrsa -out /etc/ssl/certs/server-key.pem 2048 && 
        openssl req -new -x509 -key /etc/ssl/certs/server-key.pem -out /etc/ssl/certs/server-cert.pem -days 365 -subj '/CN=yourdomain.com' && 
        openssl genrsa -out /etc/ssl/certs/ca-key.pem 2048 && 
        openssl req -new -x509 -key /etc/ssl/certs/ca-key.pem -out /etc/ssl/certs/ca-cert.pem -days 365 -subj '/CN=YourCA' && 
        openssl dhparam -out /etc/ssl/certs/dhe-param.pem 2048; 
      else 
        echo \"Certificates already exist. Skipping generation.\";
      fi
      "

  syslog-ng:
    image: balabit/syslog-ng
    privileged: true  # Grant all capabilities to this container in dev env
    volumes:
      - ./syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf
      - ./certs:/etc/syslog-ng/certs
      - ./log:/var/log
    ports:
      - "601:601"
      - "6513:6513"
      - "6514:6514"      
    depends_on:
      - openssl

  log-generator:
    image: debian:bullseye
    volumes:
      - ./log-generator.sh:/usr/local/bin/log-generator.sh
    entrypoint: ["/usr/local/bin/log-generator.sh"]
    environment:
      - SYSLOG_SERVER=syslog-ng  # Set the syslog server to the service name
      - SYSLOG_PORT=601           # Set the port to 601
