version: '3.8'

services:
  splunk-forwarder:
    image: splunk/universalforwarder:latest
    container_name: splunk-forwarder
    environment:
      SPLUNK_START_ARGS: "${SPLUNK_START_ARGS}"
      SPLUNK_PASSWORD: "${SPLUNK_PASSWORD}"
      SPLUNK_HEC_TOKEN: "${SPLUNK_HEC_TOKEN}"
      SPLUNK_HEC_URL: "${SPLUNK_HEC_URL}"
      SSL_CERT_PATH: "${SSL_CERT_PATH}"  # Optional, if you're dynamically setting certs in .env
      SSL_CA_PATH: "${SSL_CA_PATH}"      # Optional, if you're dynamically setting certs in .env
      SSL_PRIVATE_KEY_PATH: "${SSL_PRIVATE_KEY_PATH}"  # Optional
    volumes:
      - ./config/inputs.conf:/opt/splunkforwarder/etc/system/local/inputs.conf
      - ./config/outputs.conf:/opt/splunkforwarder/etc/system/local/outputs.conf
      - ./certs/self-signed:/opt/splunkforwarder/etc/system/ssl/self-signed   # Mount self-signed certs for syslog
      #- ./certs/splunk-cloud:/opt/splunkforwarder/etc/system/ssl/splunk-cloud  # Mount Splunk Cloud certs for HEC
      #- /path/to/your/logs:/logs  # Optional: Replace with the path to your log files
    ports:
      - "${SYSLOG_PORT}:${SYSLOG_PORT}"  # Expose syslog port (TLS)
    restart: always
