version: '3.8'


# services:
#   splunkforwarder:
#     build: .
#     environment:
#       - INSTALLER=splunkforwarder-9.3.1-0b8d769cb912-Linux-x86_64.tgz  # Specify the installer filename here
services:
  splunkforwarder:
    build:
      context: .
      dockerfile: splunkfwd.Dockerfile
      args:
        - INSTALLER=splunkforwarder-9.3.1-0b8d769cb912-Linux-x86_64.tgz
    environment:
      #- INSTALLER=splunkforwarder-9.3.1-0b8d769cb912-Linux-x86_64.tgz  # Define the installer name here
      - SPLUNK_PASSWORD=changemoi
    volumes:
      - ./config/inputs.conf:/opt/splunkforwarder/etc/system/local/inputs.conf  # You may want to persist this to a volume if needed
      - ../data/pki/private/server-combined.pem/:/opt/splunkforwarder/etc/certs/server-combined.pem
      - ../data/pki/ca.crt:/opt/splunkforwarder/etc/certs/ca-cert.pem
    ports:
      - "8089:8089"  # Expose any necessary ports
      - "26512:26512"
      - "26513:26513"
      - "26514:26514"
