version: '3.8'

services:
  easyrsa:
    build:
      context: .
      dockerfile: easyrsa.Dockerfile
      args:
        - VERSION=3.2.1
    environment:
      SERVER_NAME: server
      SERVER_IPS: 192.168.0.122,127.0.0.1
      CLIENT_NAME: client
      CLIENT_IPS: 192.168.0.122,127.0.0.1
    volumes:
      - ./data:/data
      #- ./myCA:/usr/local/easyrsa/myCA
    working_dir: /usr/local/easyrsa
    command: "./init-ca.sh"
    stdin_open: true
    tty: true
